.PHONY: clean All

All:
	@echo "----------Building project:[ Factory - Debug ]----------"
	@"$(MAKE)" -f  "Factory.mk"
clean:
	@echo "----------Cleaning project:[ Factory - Debug ]----------"
	@"$(MAKE)" -f  "Factory.mk" clean
