.PHONY: clean All

All:
	@echo "----------Building project:[ AbstractFactory - Debug ]----------"
	@"$(MAKE)" -f  "AbstractFactory.mk"
clean:
	@echo "----------Cleaning project:[ AbstractFactory - Debug ]----------"
	@"$(MAKE)" -f  "AbstractFactory.mk" clean
